spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: productservice-route
              uri: lb://productservice
              predicates:
                - Path= /api/product/**, /api/categories/**
              filters:
                - name: CircuitBreaker
                  args :
                    name: productServiceCircuitBreaker
                    fallbackUri: forward:/fallback/product

            - id: orderservice-route
              uri: lb://orderservice
              predicates:
                - Path= /api/orders/**

            - id: paymentservice-route
              uri: http://localhost:6002
              predicates:
                - Path= /api/payment/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCircuitBreaker
                    fallbackUri: forward:/fallback/payment
server:
  port:
    5001
eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka/: